# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set the default PostgreSQL username and password
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Expose the PostgreSQL port
EXPOSE 5432
